export interface InspeccionTrampaNuevo{
    id_inspec_tramp:number,
    consecutivo:string,
    fecha_hora:string,
    codigo_responsable:string,
    nombre_responsable:string,
    tipo:string,
    pais:string,
    num_trampa:number,
    latitud_trampa:number,
    longitud_trampa:number,
    finca_poblado:string,
    lote_propietario:string,
    cantidad_total:number,
    diagnostico:number,
    cantidad_diagnostico:number,
    notas:string,
    sincronizado:number
}