export const ACTIONS = {
    ACCESO_A_CONFIGURACIONES:"ACCESO_A_CONFIGURACIONES",
    EDITAR_REGISTROS_TRAMPAS:"EDITAR_REGISTROS_TRAMPAS",
    AGREGAR_REGISTROS_TRAMPAS:"AGREGAR_REGISTROS_TRAMPAS",
    EDITAR_REGISTROS_TRASPATIOS_FINCAS:"EDITAR_REGISTROS_TRASPATIOS_FINCAS",
    AGREGAR_REGISTROS_TRASPATIOS_FINCAS:"AGREGAR_REGISTROS_TRASPATIOS_FINCAS",
    EDITAR_REGISTROS_INSP_TRASPATIOS_FINCAS:"EDITAR_REGISTROS_INSP_TRASPATIOS_FINCAS",
    AGREGAR_REGISTROS_INSP_TRASPATIOS_FINCAS:"AGREGAR_REGISTROS_INSP_TRASPATIOS_FINCAS",
    EDITAR_REGISTROS_INSP_TRAMPAS:"EDITAR_REGISTROS_INSP_TRAMPAS",
    AGREGAR_REGISTROS_INSP_TRAMPAS:"AGREGAR_REGISTROS_INSP_TRAMPAS",
    EDITAR_MARCA_A_INSPECCION:"EDITAR_MARCA_A_INSPECCION"
};