export const ACTIONS = {
    ACCESO_A_CONFIGURACIONES:"ACCESO_A_CONFIGURACIONES",
    LEER_REGISTROS_TRAMPAS:"LEER_REGISTROS_TRAMPAS",
    EDITAR_REGISTROS_TRAMPAS:"EDITAR_REGISTROS_TRAMPAS",
    AGREGAR_REGISTROS_TRAMPAS:"AGREGAR_REGISTROS_TRAMPAS",
    LEER_REGISTROS_TRASPATIOS_FINCAS:"LEER_REGISTROS_TRASPATIOS_FINCAS",
    EDITAR_REGISTROS_TRASPATIOS_FINCAS:"EDITAR_REGISTROS_TRASPATIOS_FINCAS",
    AGREGAR_REGISTROS_TRASPATIOS_FINCAS:"AGREGAR_REGISTROS_TRASPATIOS_FINCAS",
    LEER_REGISTROS_INSP_TRASPATIOS_FINCAS:"LEER_REGISTROS_INSP_TRASPATIOS_FINCAS",
    EDITAR_REGISTROS_INSP_TRASPATIOS_FINCAS:"EDITAR_REGISTROS_INSP_TRASPATIOS_FINCAS",
    AGREGAR_REGISTROS_INSP_TRASPATIOS_FINCAS:"AGREGAR_REGISTROS_INSP_TRASPATIOS_FINCAS",
    LEER_REGISTROS_INSP_TRAMPAS:"LEER_REGISTROS_INSP_TRAMPAS",
    EDITAR_REGISTROS_INSP_TRAMPAS:"EDITAR_REGISTROS_INSP_TRAMPAS",
    AGREGAR_REGISTROS_INSP_TRAMPAS:"AGREGAR_REGISTROS_INSP_TRAMPAS",
    QUITAR_MARCA_A_INSPECCION:"QUITAR_MARCA_A_INSPECCION"
};